name: morph_opt
channels:
 - pytorch
dependencies:
 - python=3.8
 - pytorch
 - torchvision
 - cpuonly
 - psutil
 - numpy
 - scipy
 - pandas
 - matplotlib
 - seaborn
 - imageio
 - cloudpickle
 - pyyaml
 - pip
 - pip:
  #  - --find-links https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
   - dm_control
  #  - gym[mujoco]
   - stable_baselines3
   - opencv-python
   - torch-scatter
   - torch-sparse
   - torch-cluster
   - torch-spline-conv
   - torch-geometric
